Minor test updates.

diff --git a/mongo-stop b/mongo-stop
--- a/mongo-stop
+++ b/mongo-stop
@@ -5,6 +5,7 @@ CWD=$(realpath $(dirname $0))
 
 LOGFILE=$CWD/logs/mongodb.log
 PIDFILE=$CWD/logs/mongodb.pid
+MONGOPID=""
 
 mongodb_usage() {
 	echo
@@ -14,38 +15,40 @@ mongodb_usage() {
 
 mongodb_is_running() {
 	
-	MONGOPID=$(pgrep mongod || 0)
-	echo "MONGOPID = ${MONGOPID}"
-	
-	[ ${MONGOPID} -a -f /proc/${MONGOPID}/exe ] \
+	MONGOPID=$(pgrep mongod || { echo "pgrep failed."; return 0; })
+	[ "${MONGOPID}" = "" ] && { echo "PID is ${MONGOPID}"; } || { echo "Not running"; exit 1; }
+
+	[ ${MONGOPID} -a -f /proc/${MONGOPID}/exe 2>&1 > /dev/null ] \
 		&& {
-			echo "${WHITE}Found pid ${GREEN}${MONGOPID}${WHITE} at $(ls -1 /proc/${MONGOPID}/exe)"
-			return 0
+			return 1
 		} \
 		|| {
-			echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
-			return 1
+			return 0
 		}
 }
 
 mongodb_stop() {
 
-	if [ $(mongodb_is_running) -gt 0 ]; then
+	if [ mongodb_is_running ]; then
+		echo "${WHITE}Found pid ${GREEN}[${MONGOPID}]${WHITE} at /proc/${MONGOPID}/exe${RESTORE}"
 		echo -n "${YELLOW}Shutting server down:  "
 		CNT=0
-		while [ -f /proc/${pid}/exe ]
+		while [ -f /proc/${MONGOPID}/exe ]
 		do
-	  		((CNT++))
-	  		echo -ne "\b${RED}${CNT}${RESTORE}"
-			pkill -INT ${pid}
-	  		sleep 1
-	  	done
+  		((CNT++))
+  		echo -ne "\b${RED}${CNT}${RESTORE}"
+			kill -INT ${pid}
+  		sleep 1
+  	done
 		echo -e "\b${GREEN} OK ${RESTORE}"
+	else
+		echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
 	fi
 }
 
 mongodb_start() {
-	if [ $(mongodb_is_running) -eq 0 ]; then
+	if [ ! mongodb_is_running ]; then
+		echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
 		echo -n "${YELLOW}Starting server up:  "
 
 		/opt/mongodb/bin/mongod \
@@ -56,16 +59,17 @@ mongodb_start() {
 			--logpath  $LOGFILE
 
 		CNT=0
-		while [ ! -f /proc/${pid}/exe ]
+		while [ ! mongodb_is_running ]
 		do
 	  		((CNT++))
 	  		echo -ne "\b${RED}${CNT}${RESTORE}"
 	  		sleep 1
 	  	done
 		echo -e "\b${GREEN} OK ${RESTORE}"
+	else
+		echo "${WHITE}Found pid ${GREEN}[${MONGOPID}]${WHITE} at /proc/${MONGOPID}/exe"
 	fi
 }
-
 
 case "$1" in
 	'start')
@@ -86,7 +90,7 @@ case "$1" in
 			mongodb_stop
 		} \
 		|| {
-			echo "${RED} Unknown option: ${WHITE} $1 ${RESTORE}"
+			echo -e "\n${RED} Unknown option: ${WHITE} $1 ${RESTORE}\n"
 			mongodb_usage
 		}
 		;;
