Working script, I think.

diff --git a/mongo-stop b/mongo-stop
--- a/mongo-stop
+++ b/mongo-stop
@@ -15,28 +15,30 @@ mongodb_usage() {
 
 mongodb_is_running() {
 	
-	MONGOPID=$(pgrep mongod || { echo "pgrep failed."; echo 0; })
-	[ ! "${MONGOPID}" = "0" ] \
+	local MONGOPID=$(pgrep mongod || { echo 0; })
+#	[ ! "${MONGOPID}" = "0" ] \
+#		&& {
+#			#echo "${WHITE}MongoDB is running PID:${GREEN} ${MONGOPID} ${RESTORE}"
+#			DONOTHING=${MONGOPID}
+#		} \
+#		|| {
+#			#echo "${RED}MongoDB is not running${RESTORE}"
+#			return 1
+#		}
+	echo ${MONGOPID}
+	[ -f /proc/${MONGOPID}/exe 2>&1 > /dev/null ] \
 		&& {
-			echo "PID is ${MONGOPID}"
-		} \
-		|| {
-			echo "Not running"
-			exit 1
-		}
-
-	[ ${MONGOPID} -a -f /proc/${MONGOPID}/exe 2>&1 > /dev/null ] \
-		&& {
-			return 1
-		} \
-		|| {
 			return 0
+		} \
+		|| {
+			return 1
 		}
 }
 
 mongodb_stop() {
+	MONGOPID=$(mongodb_is_running)
 
-	if [ mongodb_is_running ]; then
+	if [ ${MONGOPID} -ne 0 ]; then
 		echo "${WHITE}Found pid ${GREEN}[${MONGOPID}]${WHITE} at /proc/${MONGOPID}/exe${RESTORE}"
 		echo -n "${YELLOW}Shutting server down:  "
 		CNT=0
@@ -44,7 +46,7 @@ mongodb_stop() {
 		do
   		((CNT++))
   		echo -ne "\b${RED}${CNT}${RESTORE}"
-			kill -INT ${pid}
+			kill -INT ${MONGOPID}
   		sleep 1
   	done
 		echo -e "\b${GREEN} OK ${RESTORE}"
@@ -54,19 +56,25 @@ mongodb_stop() {
 }
 
 mongodb_start() {
-	if [ ! mongodb_is_running ]; then
+	MONGOPID=$(mongodb_is_running)
+
+	if [ ${MONGOPID} -eq 0 ]; then
 		echo "${WHITE}mongod server is${RED} NOT ${WHITE}running${RESTORE}"
-		echo -n "${YELLOW}Starting server up:  "
+		echo -n "${YELLOW}Starting server up:${RESTORE}"
 
 		/opt/mongodb/bin/mongod \
 			--dbpath $CWD/data \
 			--bind_ip 192.168.1.70,localhost \
 			--fork \
 			--pidfilepath $PIDFILE \
-			--logpath  $LOGFILE
+			--logpath  $LOGFILE 2>&1 > /dev/null \
+			|| {
+				echo -e "\n${RED} Start failed. ${RESTORE}\n"
+				return 1
+			}
 
 		CNT=0
-		while [ ! mongodb_is_running ]
+		while [ "$(mongodb_is_running)" -eq 0 ]
 		do
 	  		((CNT++))
 	  		echo -ne "\b${RED}${CNT}${RESTORE}"
@@ -86,7 +94,14 @@ case "$1" in
 		mongodb_stop
 		;;
 	'status')
-		mongodb_is_running
+		MONGOPID=$(mongodb_is_running)
+		[ "${MONGOPID}" -ne 0  ] \
+			&& {
+				echo "${WHITE}MongoDB is running PID:${GREEN} ${MONGOPID} ${RESTORE}"
+			} \
+			|| {
+				echo "${RED}MongoDB is not running${RESTORE}"
+			}
 		;;
 	'help')
 		mongodb_usage
